### PR TITLE
Fix dependabot not deploying on #main

### PR DESCRIPTION
**Pull request by juliangruber**
See https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544

### CODE REVIEW

**Comment by juliangruber** [comment]
@bajtos hindsight please

**Review by bajtos — COMMENTED** [review]
🤦🏻 

Thank you for finding a way how to make this work!

**Comment by bajtos** [comment]
Should we deploy this fix to all other GH repos that are automatically deployed to Fly.io from the main branch? I think they are subject to the same problem.
- [ ] spark-api
- [ ] spark-evaluate
- [ ] spark-stats
- Anything else?

**Comment by juliangruber** [comment]
I think yes, at it's a blind spot and unexpected behavior

**Comment by bajtos** [comment]
@juliangruber I don't remember in which issue we discussed this problem earlier this week.

AFAICT, dependabot updates are still not triggering deployment from the `main` branch.

Screenshot 2024-09-06 at 10 28 58

PR not deployed: https://github.com/filecoin-station/core-fly/pull/54

**Comment by bajtos** [comment]
The commit that did not trigger our CI & CD workflow:
https://github.com/filecoin-station/core-fly/commit/3b11a2bd905c9838cdf819b0cf0078242cfdbfd4

**Comment by juliangruber** [comment]
Ok trying https://github.com/filecoin-station/core-fly/commit/c6c20228b99e885e65db6d6587320f2fd7a7bee2. It was still committing as dependabot[bot]

**Pull request merged**
